Correct failing test due to the #call kwarg dictionary being generated with unicode keys
Test failures like this:
	Traceback (most recent call last):
	  File "/home/tyler/source/github/cheetah/src/Tests/SyntaxAndOutput.py", line 1173, in test4
		"1235 FOO - upper")
	  File "/home/tyler/source/github/cheetah/src/Tests/SyntaxAndOutput.py", line 194, in verify
		output = templateObj.respond() # rather than __str__, because of unicode
	  File "cheetah_DynamicallyCompiledCheetahTemplate_1240479809_54_46184.py", line 137, in respond
	TypeError: meth() keywords must be strings

Should now be resolved.

mantis #15

Signed-off-by: R. Tyler Ballance <tyler@slide.com>